### ISSUE TITLE
mycobot_moveit.urdf.xacro does not exist.

### ISSUE THREAD

**Issue by Ry0** [mertcookimg/mycobot_controller#1]
Thank you for providing the good repository.

The following .xacro file in `planning_context.launch` does not exist and I think I should fix it. 
I used `mycobot.urdf.xacro` instead.

https://github.com/mertcookimg/mycobot_controller/blob/bb8e32e3a9ba7803cfb35f79b7af8df5ab33940a/launch/planning_context.launch#L9

There is one problem that may be related to it.

```bash
roslaunch mycobot_controller demo_mycobot.launch
```
There is the problem when I run the above launch file. The end-effector is always red and collide.

![image](https://user-images.githubusercontent.com/8924325/107541251-46e7c800-6c0a-11eb-831a-57952a834afb.png)

So, I overwrote the srdf file here to deal with it.
https://github.com/Tiryoh/mycobot_ros/blob/main/mycobot_move_it_config/config/mycobot.srdf

Probably it will be solved if mycobot_moveit.urdf.xacro exists.
Thank you very much.

**Comment by mertcookimg** [comment]
Thank you for your good issue!

What you are saying is correct.
I added mycobot_moveit.urdf.xacro in the repository. (https://github.com/mertcookimg/mycobot_ros/tree/feature/add-slider-control/mycobot_description/urdf)

Maybe we can solve this issue.
Thank you very much.

**Comment by Ry0** [comment]
After updating, the problem has been resolved.
Thank you for your support!!

I'll close this issue.
